server:
  port: 8051
### light-job, datasource
### datasource-pool
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/light_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: cn.mysql.cj.jdbc.Driver
    type: cn.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

lightjob:
  channel: redis